taxi_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: zoomcamp-postgres
      port: 5432
      user: zoomcamp
      password: zoomcamp
      dbname: zoomcamp
      schema: analytics
      threads: 4
